### ISSUE TITLE
Bug on pages with paging.

### ISSUE THREAD

**Issue by ilinandrii** [niralittle/Notus#23]
When you access the page, where is available page selection, you click on one of the page numbers and get to the specific page, but then in address bar as a get parameter you can specify any page even inexistent and some page will appear, but error or warning should.

**Comment by Vlader2** [comment]
Àíäðåé, òû òî÷íî ïðî÷åë òåêñò, êîòîðûé íàïèñàë? :)

Â ÷åì çàêëþ÷àåòñÿ áàã è ïî÷åìó but error or warning should? Ýòî åñòü â íôð?

Íó è îôôòîï, òû âåðíóë ìåòîä â äàî ðåïîðòîâ ñ ðåçàëòñåòîì, òåëî êîòîðîãî óäàëèë è íàïèñàë êàêîé-òî íåêðàñèâûé êîììåíò, íà êîòîðûé òåáå óêàçàë Èãîðü íà ïîñëåäíåé âñòðå÷å ?

## 

Best regards,
Vladimir Ermolenko

**Comment by ilinandrii** [comment]
На что он мне указывал я помню, вчера привел в порядок весь код репортов. Ну, если не считаешь это багом, то закрывай.

**Comment by Vlader2** [comment]
Андрей, что такое баг?

A software bug is an error, flaw, failure, or fault in a computer program orsystem that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

Что из перечисленного попадает в наш пейджинг?

А если я напишу в сад, что предполагается, что в урле страницы не вводятся? И по итогу it works by design.

Это не баг, это некорректный дизайн, который, согласен, надо бы улучшить.

По коду репортов - спасибо, хотя достаточно было не удалять с не очень понятным комментом часть чужого метода:) Если метод не используется - удаляй его целиком, но не выставляй автора нехорошим программистом перед кураторами :)

## 

Best regards,
Vladimir Ermolenko
